# Generated by Django 5.0.4 on 2024-04-08 13:44

from django.db import migrations, models

# https://docs.djangoproject.com/en/2.2/ref/models/fields/#model-field-types
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('dt_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
            ],
        ),
    ]
